server:
  port : 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
  
spring:
#  security:
#    user:
#      name: test
#      password: 1234
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 340783847331-mratq6kkuecvl91in9j8bcq8dthr6ukl.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          naver:
            client-id: bwsbd7YVF0K0bDfonWtG
            client-secret: 3auaUodve1
            scope:
            - email
            - name
            client-name: Naver
            authorization-grant-type: authorization_code 
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize 
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
            
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web1.cj3lh0t6nehi.ap-northeast-2.rds.amazonaws.com:3306/study?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: admin88
    password: 1q2w3e4r
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
        
    
mybatis:
  mapper-locations:
  - /mappers/*.xml
  
file: 
  path: C:/SSH/SSH/workspace/security_SSH/security_SSH/upload/

